import { CategoryMap } from "../types/candidate";
import image from "../assets/Image.svg";
export const contentMap: CategoryMap = {
  "Category 1": [
    {
      id: 1,
      name: "John Doe",
      partyName: "Party A",
      description: "John Doe is a candidate for Category 1.",
      image: image,
    },
    {
      id: 2,
      name: "Jane Smith",
      partyName: "Party B",
      description: "Jane Smith is a candidate for Category 1.",
      image: image,
    },
    {
      id: 3,
      name: "Jim Brown",
      partyName: "Party C",
      description: "Jim Brown is a candidate for Category 1.",
      image: image,
    },
    {
      id: 4,
      name: "Emily White",
      partyName: "Party D",
      description: "Emily White is a candidate for Category 1.",
      image: image,
    },
    {
      id: 5,
      name: "Michael Johnson",
      partyName: "Party E",
      description: "Michael Johnson is a candidate for Category 1.",
      image: image,
    },
    {
      id: 6,
      name: "Sarah Wilson",
      partyName: "Party F",
      description: "Sarah Wilson is a candidate for Category 1.",
      image: image,
    },
    {
      id: 7,
      name: "David Brown",
      partyName: "Party G",
      description: "David Brown is a candidate for Category 1.",
      image: image,
    },
  ],
  "Category 2": [
    {
      id: 1,
      name: "Emma Johnson",
      partyName: "Party A",
      description: "Emma Johnson is a candidate for Category 2.",
      image: image,
    },
    {
      id: 2,
      name: "Chris White",
      partyName: "Party B",
      description: "Chris White is a candidate for Category 2.",
      image: image,
    },
    {
      id: 3,
      name: "Grace Lee",
      partyName: "Party C",
      description: "Grace Lee is a candidate for Category 2.",
      image: image,
    },
    {
      id: 4,
      name: "Sam Brown",
      partyName: "Party D",
      description: "Sam Brown is a candidate for Category 2.",
      image: image,
    },
    {
      id: 5,
      name: "Alex Wilson",
      partyName: "Party E",
      description: "Alex Wilson is a candidate for Category 2.",
      image: image,
    },
    {
      id: 6,
      name: "Lucy Green",
      partyName: "Party F",
      description: "Lucy Green is a candidate for Category 2.",
      image: image,
    },
    {
      id: 7,
      name: "Daniel Smith",
      partyName: "Party G",
      description: "Daniel Smith is a candidate for Category 2.",
      image: image,
    },
  ],
  "Category 3": [
    {
      id: 1,
      name: "Emma Johnson",
      partyName: "Party A",
      description: "Emma Johnson is a candidate for Category 2.",
      image: image,
    },
    {
      id: 2,
      name: "Chris White",
      partyName: "Party B",
      description: "Chris White is a candidate for Category 2.",
      image: image,
    },
    {
      id: 3,
      name: "Grace Lee",
      partyName: "Party C",
      description: "Grace Lee is a candidate for Category 2.",
      image: image,
    },
    {
      id: 4,
      name: "Sam Brown",
      partyName: "Party D",
      description: "Sam Brown is a candidate for Category 2.",
      image: image,
    },
    {
      id: 5,
      name: "Alex Wilson",
      partyName: "Party E",
      description: "Alex Wilson is a candidate for Category 2.",
      image: image,
    },
    {
      id: 6,
      name: "Lucy Green",
      partyName: "Party F",
      description: "Lucy Green is a candidate for Category 2.",
      image: image,
    },
    {
      id: 7,
      name: "Daniel Smith",
      partyName: "Party G",
      description: "Daniel Smith is a candidate for Category 2.",
      image: image,
    },
  ],
  "Category 4": [
    {
      id: 1,
      name: "Emma Johnson",
      partyName: "Party A",
      description: "Emma Johnson is a candidate for Category 2.",
      image: image,
    },
    {
      id: 2,
      name: "Chris White",
      partyName: "Party B",
      description: "Chris White is a candidate for Category 2.",
      image: image,
    },
    {
      id: 3,
      name: "Grace Lee",
      partyName: "Party C",
      description: "Grace Lee is a candidate for Category 2.",
      image: image,
    },
    {
      id: 4,
      name: "Sam Brown",
      partyName: "Party D",
      description: "Sam Brown is a candidate for Category 2.",
      image: image,
    },
    {
      id: 5,
      name: "Alex Wilson",
      partyName: "Party E",
      description: "Alex Wilson is a candidate for Category 2.",
      image: image,
    },
    {
      id: 6,
      name: "Lucy Green",
      partyName: "Party F",
      description: "Lucy Green is a candidate for Category 2.",
      image: image,
    },
    {
      id: 7,
      name: "Daniel Smith",
      partyName: "Party G",
      description: "Daniel Smith is a candidate for Category 2.",
      image: image,
    },
  ],
  "Category 5": [
    {
      id: 1,
      name: "Emma Johnson",
      partyName: "Party A",
      description: "Emma Johnson is a candidate for Category 2.",
      image: image,
    },
    {
      id: 2,
      name: "Chris White",
      partyName: "Party B",
      description: "Chris White is a candidate for Category 2.",
      image: image,
    },
    {
      id: 3,
      name: "Grace Lee",
      partyName: "Party C",
      description: "Grace Lee is a candidate for Category 2.",
      image: image,
    },
    {
      id: 4,
      name: "Sam Brown",
      partyName: "Party D",
      description: "Sam Brown is a candidate for Category 2.",
      image: image,
    },
    {
      id: 5,
      name: "Alex Wilson",
      partyName: "Party E",
      description: "Alex Wilson is a candidate for Category 2.",
      image: image,
    },
    {
      id: 6,
      name: "Lucy Green",
      partyName: "Party F",
      description: "Lucy Green is a candidate for Category 2.",
      image: image,
    },
    {
      id: 7,
      name: "Daniel Smith",
      partyName: "Party G",
      description: "Daniel Smith is a candidate for Category 2.",
      image: image,
    },
  ],
  "Category 6": [
    {
      id: 1,
      name: "Emma Johnson",
      partyName: "Party A",
      description: "Emma Johnson is a candidate for Category 2.",
      image: image,
    },
    {
      id: 2,
      name: "Chris White",
      partyName: "Party B",
      description: "Chris White is a candidate for Category 2.",
      image: image,
    },
    {
      id: 3,
      name: "Grace Lee",
      partyName: "Party C",
      description: "Grace Lee is a candidate for Category 2.",
      image: image,
    },
    {
      id: 4,
      name: "Sam Brown",
      partyName: "Party D",
      description: "Sam Brown is a candidate for Category 2.",
      image: image,
    },
    {
      id: 5,
      name: "Alex Wilson",
      partyName: "Party E",
      description: "Alex Wilson is a candidate for Category 2.",
      image: image,
    },
    {
      id: 6,
      name: "Lucy Green",
      partyName: "Party F",
      description: "Lucy Green is a candidate for Category 2.",
      image: image,
    },
    {
      id: 7,
      name: "Daniel Smith",
      partyName: "Party G",
      description: "Daniel Smith is a candidate for Category 2.",
      image: image,
    },
  ],
  "Category 7": [
    {
      id: 1,
      name: "Emma Johnson",
      partyName: "Party A",
      description: "Emma Johnson is a candidate for Category 2.",
      image: image,
    },
    {
      id: 2,
      name: "Chris White",
      partyName: "Party B",
      description: "Chris White is a candidate for Category 2.",
      image: image,
    },
    {
      id: 3,
      name: "Grace Lee",
      partyName: "Party C",
      description: "Grace Lee is a candidate for Category 2.",
      image: image,
    },
    {
      id: 4,
      name: "Sam Brown",
      partyName: "Party D",
      description: "Sam Brown is a candidate for Category 2.",
      image: image,
    },
    {
      id: 5,
      name: "Alex Wilson",
      partyName: "Party E",
      description: "Alex Wilson is a candidate for Category 2.",
      image: image,
    },
    {
      id: 6,
      name: "Lucy Green",
      partyName: "Party F",
      description: "Lucy Green is a candidate for Category 2.",
      image: image,
    },
    {
      id: 7,
      name: "Daniel Smith",
      partyName: "Party G",
      description: "Daniel Smith is a candidate for Category 2.",
      image: image,
    },
  ],
  "Category 8": [
    {
      id: 1,
      name: "Emma Johnson",
      partyName: "Party A",
      description: "Emma Johnson is a candidate for Category 2.",
      image: image,
    },
    {
      id: 2,
      name: "Chris White",
      partyName: "Party B",
      description: "Chris White is a candidate for Category 2.",
      image: image,
    },
    {
      id: 3,
      name: "Grace Lee",
      partyName: "Party C",
      description: "Grace Lee is a candidate for Category 2.",
      image: image,
    },
    {
      id: 4,
      name: "Sam Brown",
      partyName: "Party D",
      description: "Sam Brown is a candidate for Category 2.",
      image: image,
    },
    {
      id: 5,
      name: "Alex Wilson",
      partyName: "Party E",
      description: "Alex Wilson is a candidate for Category 2.",
      image: image,
    },
    {
      id: 6,
      name: "Lucy Green",
      partyName: "Party F",
      description: "Lucy Green is a candidate for Category 2.",
      image: image,
    },
    {
      id: 7,
      name: "Daniel Smith",
      partyName: "Party G",
      description: "Daniel Smith is a candidate for Category 2.",
      image: image,
    },
  ],
  "Category 9": [
    {
      id: 1,
      name: "Emma Johnson",
      partyName: "Party A",
      description: "Emma Johnson is a candidate for Category 2.",
      image: image,
    },
    {
      id: 2,
      name: "Chris White",
      partyName: "Party B",
      description: "Chris White is a candidate for Category 2.",
      image: image,
    },
    {
      id: 3,
      name: "Grace Lee",
      partyName: "Party C",
      description: "Grace Lee is a candidate for Category 2.",
      image: image,
    },
    {
      id: 4,
      name: "Sam Brown",
      partyName: "Party D",
      description: "Sam Brown is a candidate for Category 2.",
      image: image,
    },
    {
      id: 5,
      name: "Alex Wilson",
      partyName: "Party E",
      description: "Alex Wilson is a candidate for Category 2.",
      image: image,
    },
    {
      id: 6,
      name: "Lucy Green",
      partyName: "Party F",
      description: "Lucy Green is a candidate for Category 2.",
      image: image,
    },
    {
      id: 7,
      name: "Daniel Smith",
      partyName: "Party G",
      description: "Daniel Smith is a candidate for Category 2.",
      image: image,
    },
  ],
  "Category 10": [
    {
      id: 1,
      name: "Emma Johnson",
      partyName: "Party A",
      description: "Emma Johnson is a candidate for Category 2.",
      image: image,
    },
    {
      id: 2,
      name: "Chris White",
      partyName: "Party B",
      description: "Chris White is a candidate for Category 2.",
      image: image,
    },
    {
      id: 3,
      name: "Grace Lee",
      partyName: "Party C",
      description: "Grace Lee is a candidate for Category 2.",
      image: image,
    },
    {
      id: 4,
      name: "Sam Brown",
      partyName: "Party D",
      description: "Sam Brown is a candidate for Category 2.",
      image: image,
    },
    {
      id: 5,
      name: "Alex Wilson",
      partyName: "Party E",
      description: "Alex Wilson is a candidate for Category 2.",
      image: image,
    },
    {
      id: 6,
      name: "Lucy Green",
      partyName: "Party F",
      description: "Lucy Green is a candidate for Category 2.",
      image: image,
    },
    {
      id: 7,
      name: "Daniel Smith",
      partyName: "Party G",
      description: "Daniel Smith is a candidate for Category 2.",
      image: image,
    },
  ],
};
